/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppReferralsModel
 */
export interface AppReferralsModel {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof AppReferralsModel
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof AppReferralsModel
     */
    appId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof AppReferralsModel
     */
    referredUserId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof AppReferralsModel
     */
    referrerUserId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof AppReferralsModel
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof AppReferralsModel
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the AppReferralsModel interface.
 */
export function instanceOfAppReferralsModel(value: object): value is AppReferralsModel {
    return true;
}

export function AppReferralsModelFromJSON(json: any): AppReferralsModel {
    return AppReferralsModelFromJSONTyped(json, false);
}

export function AppReferralsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReferralsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'referredUserId': json['referredUserId'] == null ? undefined : json['referredUserId'],
        'referrerUserId': json['referrerUserId'] == null ? undefined : json['referrerUserId'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function AppReferralsModelToJSON(value?: AppReferralsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'referredUserId': value['referredUserId'],
        'referrerUserId': value['referrerUserId'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
    };
}

