/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractModel
 */
export interface ContractModel {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    appId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    userId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    templateId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    chain?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof ContractModel
     */
    abi?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    address?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    name?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    description?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof ContractModel
     */
    metadata?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof ContractModel
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the ContractModel interface.
 */
export function instanceOfContractModel(value: object): value is ContractModel {
    return true;
}

export function ContractModelFromJSON(json: any): ContractModel {
    return ContractModelFromJSONTyped(json, false);
}

export function ContractModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'templateId': json['templateId'] == null ? undefined : json['templateId'],
        'chain': json['chain'] == null ? undefined : json['chain'],
        'abi': json['abi'] == null ? undefined : json['abi'],
        'address': json['address'] == null ? undefined : json['address'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function ContractModelToJSON(value?: ContractModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'userId': value['userId'],
        'templateId': value['templateId'],
        'chain': value['chain'],
        'abi': value['abi'],
        'address': value['address'],
        'name': value['name'],
        'description': value['description'],
        'metadata': value['metadata'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
    };
}

