/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAppRequest
 */
export interface CreateAppRequest {
    /**
     * The assetId of the icon image. Icon images are recommended to be a 1:1 aspect ratio and at least 512x512 pixels.
     * @type {string}
     * @memberof CreateAppRequest
     */
    iconImageAssetId?: string;
    /**
     * The assetId of the background image. Background images are recommended to be a 16:9 aspect ratio and at least 1920x1080 pixels.
     * @type {string}
     * @memberof CreateAppRequest
     */
    backgroundImageAssetId?: string;
    /**
     * The assetId of the logo image. Logo image are used on pages like preregistration, questing, etc and can be any aspect ratio.
     * @type {string}
     * @memberof CreateAppRequest
     */
    logoImageAssetId?: string;
    /**
     * An array of assetIds for media assets to be displayed for app promotional purposes. Such as the web page media gallery.
     * @type {Array<string>}
     * @memberof CreateAppRequest
     */
    galleryMediaAssetIds?: Array<string>;
    /**
     * The name of the app.
     * @type {string}
     * @memberof CreateAppRequest
     */
    name: string;
    /**
     * A brief description of the app and what it is and does.
     * @type {string}
     * @memberof CreateAppRequest
     */
    description?: string;
    /**
     * The URL of the app, such as its website or where users can learn more about it.
     * @type {string}
     * @memberof CreateAppRequest
     */
    url?: string;
    /**
     * The URL of the app's Discord server.
     * @type {string}
     * @memberof CreateAppRequest
     */
    discordUrl?: string;
    /**
     * The URL of the app's Twitter page.
     * @type {string}
     * @memberof CreateAppRequest
     */
    twitterUrl?: string;
    /**
     * The URL of the app's Steam page.
     * @type {string}
     * @memberof CreateAppRequest
     */
    steamUrl?: string;
    /**
     * The URL of the app's Apple iOS page.
     * @type {string}
     * @memberof CreateAppRequest
     */
    appleIosUrl?: string;
    /**
     * The URL of the app's Apple Mac page.
     * @type {string}
     * @memberof CreateAppRequest
     */
    appleMacUrl?: string;
    /**
     * The URL of the app's Google Play page.
     * @type {string}
     * @memberof CreateAppRequest
     */
    googlePlayUrl?: string;
    /**
     * The URL of the app's Windows Store page.
     * @type {string}
     * @memberof CreateAppRequest
     */
    microsoftUrl?: string;
    /**
     * The URL of the app's privacy policy.
     * @type {string}
     * @memberof CreateAppRequest
     */
    privacyUrl?: string;
    /**
     * The URL of the app's terms of service.
     * @type {string}
     * @memberof CreateAppRequest
     */
    termsUrl?: string;
    /**
     * An array of valid redirect URIs for the user authorization flows of the app.
     * @type {Array<string>}
     * @memberof CreateAppRequest
     */
    redirectUris?: Array<string>;
}

/**
 * Check if a given object implements the CreateAppRequest interface.
 */
export function instanceOfCreateAppRequest(value: object): value is CreateAppRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAppRequestFromJSON(json: any): CreateAppRequest {
    return CreateAppRequestFromJSONTyped(json, false);
}

export function CreateAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iconImageAssetId': json['iconImageAssetId'] == null ? undefined : json['iconImageAssetId'],
        'backgroundImageAssetId': json['backgroundImageAssetId'] == null ? undefined : json['backgroundImageAssetId'],
        'logoImageAssetId': json['logoImageAssetId'] == null ? undefined : json['logoImageAssetId'],
        'galleryMediaAssetIds': json['galleryMediaAssetIds'] == null ? undefined : json['galleryMediaAssetIds'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'discordUrl': json['discordUrl'] == null ? undefined : json['discordUrl'],
        'twitterUrl': json['twitterUrl'] == null ? undefined : json['twitterUrl'],
        'steamUrl': json['steamUrl'] == null ? undefined : json['steamUrl'],
        'appleIosUrl': json['appleIosUrl'] == null ? undefined : json['appleIosUrl'],
        'appleMacUrl': json['appleMacUrl'] == null ? undefined : json['appleMacUrl'],
        'googlePlayUrl': json['googlePlayUrl'] == null ? undefined : json['googlePlayUrl'],
        'microsoftUrl': json['microsoftUrl'] == null ? undefined : json['microsoftUrl'],
        'privacyUrl': json['privacyUrl'] == null ? undefined : json['privacyUrl'],
        'termsUrl': json['termsUrl'] == null ? undefined : json['termsUrl'],
        'redirectUris': json['redirectUris'] == null ? undefined : json['redirectUris'],
    };
}

export function CreateAppRequestToJSON(value?: CreateAppRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'iconImageAssetId': value['iconImageAssetId'],
        'backgroundImageAssetId': value['backgroundImageAssetId'],
        'logoImageAssetId': value['logoImageAssetId'],
        'galleryMediaAssetIds': value['galleryMediaAssetIds'],
        'name': value['name'],
        'description': value['description'],
        'url': value['url'],
        'discordUrl': value['discordUrl'],
        'twitterUrl': value['twitterUrl'],
        'steamUrl': value['steamUrl'],
        'appleIosUrl': value['appleIosUrl'],
        'appleMacUrl': value['appleMacUrl'],
        'googlePlayUrl': value['googlePlayUrl'],
        'microsoftUrl': value['microsoftUrl'],
        'privacyUrl': value['privacyUrl'],
        'termsUrl': value['termsUrl'],
        'redirectUris': value['redirectUris'],
    };
}

