/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLeaderboard200Response
 */
export interface CreateLeaderboard200Response {
    /**
     * The leaderboard ID.
     * @type {string}
     * @memberof CreateLeaderboard200Response
     */
    id?: string;
    /**
     * The leaderboard name.
     * @type {string}
     * @memberof CreateLeaderboard200Response
     */
    name?: string;
    /**
     * The leaderboard description.
     * @type {string}
     * @memberof CreateLeaderboard200Response
     */
    description?: string;
    /**
     * The leaderboard scores, keyed by user ID, defaults to an empty object.
     * @type {object}
     * @memberof CreateLeaderboard200Response
     */
    scores?: object;
    /**
     * The leaderboard hash key, used to generate hashes for client side submission of scores.
     * @type {string}
     * @memberof CreateLeaderboard200Response
     */
    key?: string;
    /**
     * The timestamp of the leaderboard creation in seconds since the Unix epoch.
     * @type {number}
     * @memberof CreateLeaderboard200Response
     */
    createdAt?: number;
}

/**
 * Check if a given object implements the CreateLeaderboard200Response interface.
 */
export function instanceOfCreateLeaderboard200Response(value: object): value is CreateLeaderboard200Response {
    return true;
}

export function CreateLeaderboard200ResponseFromJSON(json: any): CreateLeaderboard200Response {
    return CreateLeaderboard200ResponseFromJSONTyped(json, false);
}

export function CreateLeaderboard200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLeaderboard200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'scores': json['scores'] == null ? undefined : json['scores'],
        'key': json['key'] == null ? undefined : json['key'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function CreateLeaderboard200ResponseToJSON(value?: CreateLeaderboard200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'scores': value['scores'],
        'key': value['key'],
        'createdAt': value['createdAt'],
    };
}

