/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAssetRequest
 */
export interface CreateAssetRequest {
    /**
     * The base64 string of the asset being uploaded. Uploads may not exceed 5mb.
     * @type {string}
     * @memberof CreateAssetRequest
     */
    fileBase64?: string;
}

/**
 * Check if a given object implements the CreateAssetRequest interface.
 */
export function instanceOfCreateAssetRequest(value: object): value is CreateAssetRequest {
    return true;
}

export function CreateAssetRequestFromJSON(json: any): CreateAssetRequest {
    return CreateAssetRequestFromJSONTyped(json, false);
}

export function CreateAssetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAssetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileBase64': json['fileBase64'] == null ? undefined : json['fileBase64'],
    };
}

export function CreateAssetRequestToJSON(value?: CreateAssetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileBase64': value['fileBase64'],
    };
}

