/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLeaderboardRequest
 */
export interface CreateLeaderboardRequest {
    /**
     * The leaderboard name.
     * @type {string}
     * @memberof CreateLeaderboardRequest
     */
    name: string;
    /**
     * The leaderboard description.
     * @type {string}
     * @memberof CreateLeaderboardRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateLeaderboardRequest interface.
 */
export function instanceOfCreateLeaderboardRequest(value: object): value is CreateLeaderboardRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateLeaderboardRequestFromJSON(json: any): CreateLeaderboardRequest {
    return CreateLeaderboardRequestFromJSONTyped(json, false);
}

export function CreateLeaderboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLeaderboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateLeaderboardRequestToJSON(value?: CreateLeaderboardRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

