/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAppTeammateRequest
 */
export interface CreateAppTeammateRequest {
    /**
     * The user id to add as a teammate of the app.
     * @type {string}
     * @memberof CreateAppTeammateRequest
     */
    userId: string;
    /**
     * The role of the teammate.
     * @type {string}
     * @memberof CreateAppTeammateRequest
     */
    role: CreateAppTeammateRequestRoleEnum;
}


/**
 * @export
 */
export const CreateAppTeammateRequestRoleEnum = {
    Owner: 'OWNER',
    Developer: 'DEVELOPER',
    Editor: 'EDITOR',
    Analyst: 'ANALYST'
} as const;
export type CreateAppTeammateRequestRoleEnum = typeof CreateAppTeammateRequestRoleEnum[keyof typeof CreateAppTeammateRequestRoleEnum];


/**
 * Check if a given object implements the CreateAppTeammateRequest interface.
 */
export function instanceOfCreateAppTeammateRequest(value: object): value is CreateAppTeammateRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CreateAppTeammateRequestFromJSON(json: any): CreateAppTeammateRequest {
    return CreateAppTeammateRequestFromJSONTyped(json, false);
}

export function CreateAppTeammateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppTeammateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'role': json['role'],
    };
}

export function CreateAppTeammateRequestToJSON(value?: CreateAppTeammateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'role': value['role'],
    };
}

