/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteFromWhitelistRequest
 */
export interface DeleteFromWhitelistRequest {
    /**
     * User Ids to add to the whitelist.
     * @type {Array<string>}
     * @memberof DeleteFromWhitelistRequest
     */
    userIds?: Array<string>;
    /**
     * Emails to add to the whitelist.
     * @type {Array<string>}
     * @memberof DeleteFromWhitelistRequest
     */
    emails?: Array<string>;
    /**
     * Usernames to add to the whitelist.
     * @type {Array<string>}
     * @memberof DeleteFromWhitelistRequest
     */
    usernames?: Array<string>;
}

/**
 * Check if a given object implements the DeleteFromWhitelistRequest interface.
 */
export function instanceOfDeleteFromWhitelistRequest(value: object): value is DeleteFromWhitelistRequest {
    return true;
}

export function DeleteFromWhitelistRequestFromJSON(json: any): DeleteFromWhitelistRequest {
    return DeleteFromWhitelistRequestFromJSONTyped(json, false);
}

export function DeleteFromWhitelistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFromWhitelistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIds': json['userIds'] == null ? undefined : json['userIds'],
        'emails': json['emails'] == null ? undefined : json['emails'],
        'usernames': json['usernames'] == null ? undefined : json['usernames'],
    };
}

export function DeleteFromWhitelistRequestToJSON(value?: DeleteFromWhitelistRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userIds': value['userIds'],
        'emails': value['emails'],
        'usernames': value['usernames'],
    };
}

