/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteLeaderboardScoreRequest
 */
export interface DeleteLeaderboardScoreRequest {
    /**
     * The user id to delete the score for.
     * @type {string}
     * @memberof DeleteLeaderboardScoreRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the DeleteLeaderboardScoreRequest interface.
 */
export function instanceOfDeleteLeaderboardScoreRequest(value: object): value is DeleteLeaderboardScoreRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function DeleteLeaderboardScoreRequestFromJSON(json: any): DeleteLeaderboardScoreRequest {
    return DeleteLeaderboardScoreRequestFromJSONTyped(json, false);
}

export function DeleteLeaderboardScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteLeaderboardScoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function DeleteLeaderboardScoreRequestToJSON(value?: DeleteLeaderboardScoreRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

