/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndSessionRequest
 */
export interface EndSessionRequest {
    /**
     * If the `X-App-Authorization` or `X-Session-Authorization` header is not set, `appId` must be provided to indicate the application for which to end user sessions for.
     * @type {string}
     * @memberof EndSessionRequest
     */
    appId?: string;
    /**
     * If the user's `X-Authorization` or `X-Session-Authorization` header is not set, `userId` must be provided to indicate the user for which to end sessions for.
     * @type {string}
     * @memberof EndSessionRequest
     */
    userId?: string;
    /**
     * The chain to end sessions for.
     * @type {string}
     * @memberof EndSessionRequest
     */
    chain: EndSessionRequestChainEnum;
}


/**
 * @export
 */
export const EndSessionRequestChainEnum = {
    Hychain: 'HYCHAIN',
    HychainTestnet: 'HYCHAIN_TESTNET',
    Local: 'LOCAL'
} as const;
export type EndSessionRequestChainEnum = typeof EndSessionRequestChainEnum[keyof typeof EndSessionRequestChainEnum];


/**
 * Check if a given object implements the EndSessionRequest interface.
 */
export function instanceOfEndSessionRequest(value: object): value is EndSessionRequest {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    return true;
}

export function EndSessionRequestFromJSON(json: any): EndSessionRequest {
    return EndSessionRequestFromJSONTyped(json, false);
}

export function EndSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'chain': json['chain'],
    };
}

export function EndSessionRequestToJSON(value?: EndSessionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'appId': value['appId'],
        'userId': value['userId'],
        'chain': value['chain'],
    };
}

