/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppTeammates200ResponseAllOfUser
 */
export interface GetAppTeammates200ResponseAllOfUser {
    /**
     * 
     * @type {string}
     * @memberof GetAppTeammates200ResponseAllOfUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppTeammates200ResponseAllOfUser
     */
    username?: string;
}

/**
 * Check if a given object implements the GetAppTeammates200ResponseAllOfUser interface.
 */
export function instanceOfGetAppTeammates200ResponseAllOfUser(value: object): value is GetAppTeammates200ResponseAllOfUser {
    return true;
}

export function GetAppTeammates200ResponseAllOfUserFromJSON(json: any): GetAppTeammates200ResponseAllOfUser {
    return GetAppTeammates200ResponseAllOfUserFromJSONTyped(json, false);
}

export function GetAppTeammates200ResponseAllOfUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppTeammates200ResponseAllOfUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function GetAppTeammates200ResponseAllOfUserToJSON(value?: GetAppTeammates200ResponseAllOfUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'username': value['username'],
    };
}

