/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppState200Response
 */
export interface GetAppState200Response {
    /**
     * Public state data for the app or user.
     * @type {object}
     * @memberof GetAppState200Response
     */
    publicState?: object;
    /**
     * Protected state data for the app or user.
     * @type {object}
     * @memberof GetAppState200Response
     */
    protectedState?: object;
    /**
     * Private state data for the app or user.
     * @type {object}
     * @memberof GetAppState200Response
     */
    privateState?: object;
}

/**
 * Check if a given object implements the GetAppState200Response interface.
 */
export function instanceOfGetAppState200Response(value: object): value is GetAppState200Response {
    return true;
}

export function GetAppState200ResponseFromJSON(json: any): GetAppState200Response {
    return GetAppState200ResponseFromJSONTyped(json, false);
}

export function GetAppState200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppState200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'publicState': json['publicState'] == null ? undefined : json['publicState'],
        'protectedState': json['protectedState'] == null ? undefined : json['protectedState'],
        'privateState': json['privateState'] == null ? undefined : json['privateState'],
    };
}

export function GetAppState200ResponseToJSON(value?: GetAppState200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'publicState': value['publicState'],
        'protectedState': value['protectedState'],
        'privateState': value['privateState'],
    };
}

