/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAppTeammates200ResponseAllOfUser } from './GetAppTeammates200ResponseAllOfUser';
import {
    GetAppTeammates200ResponseAllOfUserFromJSON,
    GetAppTeammates200ResponseAllOfUserFromJSONTyped,
    GetAppTeammates200ResponseAllOfUserToJSON,
} from './GetAppTeammates200ResponseAllOfUser';

/**
 * 
 * @export
 * @interface GetAppTeammates200Response
 */
export interface GetAppTeammates200Response {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppTeammates200Response
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppTeammates200Response
     */
    appId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppTeammates200Response
     */
    userId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppTeammates200Response
     */
    role?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppTeammates200Response
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppTeammates200Response
     */
    createdAt?: string;
    /**
     * 
     * @type {GetAppTeammates200ResponseAllOfUser}
     * @memberof GetAppTeammates200Response
     */
    user?: GetAppTeammates200ResponseAllOfUser;
}

/**
 * Check if a given object implements the GetAppTeammates200Response interface.
 */
export function instanceOfGetAppTeammates200Response(value: object): value is GetAppTeammates200Response {
    return true;
}

export function GetAppTeammates200ResponseFromJSON(json: any): GetAppTeammates200Response {
    return GetAppTeammates200ResponseFromJSONTyped(json, false);
}

export function GetAppTeammates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppTeammates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'role': json['role'] == null ? undefined : json['role'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'user': json['user'] == null ? undefined : GetAppTeammates200ResponseAllOfUserFromJSON(json['user']),
    };
}

export function GetAppTeammates200ResponseToJSON(value?: GetAppTeammates200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'userId': value['userId'],
        'role': value['role'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
        'user': GetAppTeammates200ResponseAllOfUserToJSON(value['user']),
    };
}

