/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletModel } from './WalletModel';
import {
    WalletModelFromJSON,
    WalletModelFromJSONTyped,
    WalletModelToJSON,
} from './WalletModel';

/**
 * 
 * @export
 * @interface GetAppUsers200Response
 */
export interface GetAppUsers200Response {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    walletId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    username?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    email?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    phone?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    appleId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    discordId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    facebookId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    googleId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    microsoftId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    twitterId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    accessToken?: string;
    /**
     * This field has not had a description added.
     * @type {boolean}
     * @memberof GetAppUsers200Response
     */
    isChild?: boolean;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    accessTokenExpiresAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetAppUsers200Response
     */
    createdAt?: string;
    /**
     * 
     * @type {WalletModel}
     * @memberof GetAppUsers200Response
     */
    wallet?: WalletModel;
}

/**
 * Check if a given object implements the GetAppUsers200Response interface.
 */
export function instanceOfGetAppUsers200Response(value: object): value is GetAppUsers200Response {
    return true;
}

export function GetAppUsers200ResponseFromJSON(json: any): GetAppUsers200Response {
    return GetAppUsers200ResponseFromJSONTyped(json, false);
}

export function GetAppUsers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppUsers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'walletId': json['walletId'] == null ? undefined : json['walletId'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'appleId': json['appleId'] == null ? undefined : json['appleId'],
        'discordId': json['discordId'] == null ? undefined : json['discordId'],
        'facebookId': json['facebookId'] == null ? undefined : json['facebookId'],
        'googleId': json['googleId'] == null ? undefined : json['googleId'],
        'microsoftId': json['microsoftId'] == null ? undefined : json['microsoftId'],
        'twitterId': json['twitterId'] == null ? undefined : json['twitterId'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'isChild': json['isChild'] == null ? undefined : json['isChild'],
        'accessTokenExpiresAt': json['accessTokenExpiresAt'] == null ? undefined : json['accessTokenExpiresAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'wallet': json['wallet'] == null ? undefined : WalletModelFromJSON(json['wallet']),
    };
}

export function GetAppUsers200ResponseToJSON(value?: GetAppUsers200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'walletId': value['walletId'],
        'username': value['username'],
        'email': value['email'],
        'phone': value['phone'],
        'appleId': value['appleId'],
        'discordId': value['discordId'],
        'facebookId': value['facebookId'],
        'googleId': value['googleId'],
        'microsoftId': value['microsoftId'],
        'twitterId': value['twitterId'],
        'accessToken': value['accessToken'],
        'isChild': value['isChild'],
        'accessTokenExpiresAt': value['accessTokenExpiresAt'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
        'wallet': WalletModelToJSON(value['wallet']),
    };
}

