/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLeaderboardScore200Response
 */
export interface GetLeaderboardScore200Response {
    /**
     * 
     * @type {string}
     * @memberof GetLeaderboardScore200Response
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardScore200Response
     */
    score?: number;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardScore200Response
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the GetLeaderboardScore200Response interface.
 */
export function instanceOfGetLeaderboardScore200Response(value: object): value is GetLeaderboardScore200Response {
    return true;
}

export function GetLeaderboardScore200ResponseFromJSON(json: any): GetLeaderboardScore200Response {
    return GetLeaderboardScore200ResponseFromJSONTyped(json, false);
}

export function GetLeaderboardScore200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLeaderboardScore200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'score': json['score'] == null ? undefined : json['score'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function GetLeaderboardScore200ResponseToJSON(value?: GetLeaderboardScore200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'score': value['score'],
        'timestamp': value['timestamp'],
    };
}

