/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLeaderboardScores200ResponseScoresInner } from './GetLeaderboardScores200ResponseScoresInner';
import {
    GetLeaderboardScores200ResponseScoresInnerFromJSON,
    GetLeaderboardScores200ResponseScoresInnerFromJSONTyped,
    GetLeaderboardScores200ResponseScoresInnerToJSON,
} from './GetLeaderboardScores200ResponseScoresInner';

/**
 * 
 * @export
 * @interface GetLeaderboardScores200Response
 */
export interface GetLeaderboardScores200Response {
    /**
     * 
     * @type {Array<GetLeaderboardScores200ResponseScoresInner>}
     * @memberof GetLeaderboardScores200Response
     */
    scores?: Array<GetLeaderboardScores200ResponseScoresInner>;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardScores200Response
     */
    totalScores?: number;
}

/**
 * Check if a given object implements the GetLeaderboardScores200Response interface.
 */
export function instanceOfGetLeaderboardScores200Response(value: object): value is GetLeaderboardScores200Response {
    return true;
}

export function GetLeaderboardScores200ResponseFromJSON(json: any): GetLeaderboardScores200Response {
    return GetLeaderboardScores200ResponseFromJSONTyped(json, false);
}

export function GetLeaderboardScores200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLeaderboardScores200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scores': json['scores'] == null ? undefined : ((json['scores'] as Array<any>).map(GetLeaderboardScores200ResponseScoresInnerFromJSON)),
        'totalScores': json['totalScores'] == null ? undefined : json['totalScores'],
    };
}

export function GetLeaderboardScores200ResponseToJSON(value?: GetLeaderboardScores200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scores': value['scores'] == null ? undefined : ((value['scores'] as Array<any>).map(GetLeaderboardScores200ResponseScoresInnerToJSON)),
        'totalScores': value['totalScores'],
    };
}

