/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLeaderboardScores200ResponseScoresInner
 */
export interface GetLeaderboardScores200ResponseScoresInner {
    /**
     * 
     * @type {string}
     * @memberof GetLeaderboardScores200ResponseScoresInner
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetLeaderboardScores200ResponseScoresInner
     */
    username?: string;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardScores200ResponseScoresInner
     */
    score?: number;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardScores200ResponseScoresInner
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the GetLeaderboardScores200ResponseScoresInner interface.
 */
export function instanceOfGetLeaderboardScores200ResponseScoresInner(value: object): value is GetLeaderboardScores200ResponseScoresInner {
    return true;
}

export function GetLeaderboardScores200ResponseScoresInnerFromJSON(json: any): GetLeaderboardScores200ResponseScoresInner {
    return GetLeaderboardScores200ResponseScoresInnerFromJSONTyped(json, false);
}

export function GetLeaderboardScores200ResponseScoresInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLeaderboardScores200ResponseScoresInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
        'score': json['score'] == null ? undefined : json['score'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function GetLeaderboardScores200ResponseScoresInnerToJSON(value?: GetLeaderboardScores200ResponseScoresInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'score': value['score'],
        'timestamp': value['timestamp'],
    };
}

