/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLeaderboards200ResponseInner
 */
export interface GetLeaderboards200ResponseInner {
    /**
     * The leaderboard ID.
     * @type {string}
     * @memberof GetLeaderboards200ResponseInner
     */
    id?: string;
    /**
     * The leaderboard name.
     * @type {string}
     * @memberof GetLeaderboards200ResponseInner
     */
    name?: string;
    /**
     * The leaderboard description.
     * @type {string}
     * @memberof GetLeaderboards200ResponseInner
     */
    description?: string;
    /**
     * The total number of users with scores in the leaderboard.
     * @type {number}
     * @memberof GetLeaderboards200ResponseInner
     */
    totalScores?: number;
}

/**
 * Check if a given object implements the GetLeaderboards200ResponseInner interface.
 */
export function instanceOfGetLeaderboards200ResponseInner(value: object): value is GetLeaderboards200ResponseInner {
    return true;
}

export function GetLeaderboards200ResponseInnerFromJSON(json: any): GetLeaderboards200ResponseInner {
    return GetLeaderboards200ResponseInnerFromJSONTyped(json, false);
}

export function GetLeaderboards200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLeaderboards200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'totalScores': json['totalScores'] == null ? undefined : json['totalScores'],
    };
}

export function GetLeaderboards200ResponseInnerToJSON(value?: GetLeaderboards200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'totalScores': value['totalScores'],
    };
}

