/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPage200ResponseAllOfLeaderboard
 */
export interface GetPage200ResponseAllOfLeaderboard {
    /**
     * 
     * @type {string}
     * @memberof GetPage200ResponseAllOfLeaderboard
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetPage200ResponseAllOfLeaderboard
     */
    visible?: boolean;
}

/**
 * Check if a given object implements the GetPage200ResponseAllOfLeaderboard interface.
 */
export function instanceOfGetPage200ResponseAllOfLeaderboard(value: object): value is GetPage200ResponseAllOfLeaderboard {
    return true;
}

export function GetPage200ResponseAllOfLeaderboardFromJSON(json: any): GetPage200ResponseAllOfLeaderboard {
    return GetPage200ResponseAllOfLeaderboardFromJSONTyped(json, false);
}

export function GetPage200ResponseAllOfLeaderboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPage200ResponseAllOfLeaderboard {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'visible': json['visible'] == null ? undefined : json['visible'],
    };
}

export function GetPage200ResponseAllOfLeaderboardToJSON(value?: GetPage200ResponseAllOfLeaderboard | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'visible': value['visible'],
    };
}

