/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPage200ResponseAllOfReferral
 */
export interface GetPage200ResponseAllOfReferral {
    /**
     * 
     * @type {boolean}
     * @memberof GetPage200ResponseAllOfReferral
     */
    visible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetPage200ResponseAllOfReferral
     */
    titleText?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPage200ResponseAllOfReferral
     */
    incentiveText?: string;
}

/**
 * Check if a given object implements the GetPage200ResponseAllOfReferral interface.
 */
export function instanceOfGetPage200ResponseAllOfReferral(value: object): value is GetPage200ResponseAllOfReferral {
    return true;
}

export function GetPage200ResponseAllOfReferralFromJSON(json: any): GetPage200ResponseAllOfReferral {
    return GetPage200ResponseAllOfReferralFromJSONTyped(json, false);
}

export function GetPage200ResponseAllOfReferralFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPage200ResponseAllOfReferral {
    if (json == null) {
        return json;
    }
    return {
        
        'visible': json['visible'] == null ? undefined : json['visible'],
        'titleText': json['titleText'] == null ? undefined : json['titleText'],
        'incentiveText': json['incentiveText'] == null ? undefined : json['incentiveText'],
    };
}

export function GetPage200ResponseAllOfReferralToJSON(value?: GetPage200ResponseAllOfReferral | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'visible': value['visible'],
        'titleText': value['titleText'],
        'incentiveText': value['incentiveText'],
    };
}

