/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPage200ResponseAllOfPreregister
 */
export interface GetPage200ResponseAllOfPreregister {
    /**
     * 
     * @type {boolean}
     * @memberof GetPage200ResponseAllOfPreregister
     */
    visible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetPage200ResponseAllOfPreregister
     */
    incentiveText?: string;
}

/**
 * Check if a given object implements the GetPage200ResponseAllOfPreregister interface.
 */
export function instanceOfGetPage200ResponseAllOfPreregister(value: object): value is GetPage200ResponseAllOfPreregister {
    return true;
}

export function GetPage200ResponseAllOfPreregisterFromJSON(json: any): GetPage200ResponseAllOfPreregister {
    return GetPage200ResponseAllOfPreregisterFromJSONTyped(json, false);
}

export function GetPage200ResponseAllOfPreregisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPage200ResponseAllOfPreregister {
    if (json == null) {
        return json;
    }
    return {
        
        'visible': json['visible'] == null ? undefined : json['visible'],
        'incentiveText': json['incentiveText'] == null ? undefined : json['incentiveText'],
    };
}

export function GetPage200ResponseAllOfPreregisterToJSON(value?: GetPage200ResponseAllOfPreregister | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'visible': value['visible'],
        'incentiveText': value['incentiveText'],
    };
}

