/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPage200ResponseAllOfLinksInner
 */
export interface GetPage200ResponseAllOfLinksInner {
    /**
     * 
     * @type {string}
     * @memberof GetPage200ResponseAllOfLinksInner
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPage200ResponseAllOfLinksInner
     */
    url?: string;
}

/**
 * Check if a given object implements the GetPage200ResponseAllOfLinksInner interface.
 */
export function instanceOfGetPage200ResponseAllOfLinksInner(value: object): value is GetPage200ResponseAllOfLinksInner {
    return true;
}

export function GetPage200ResponseAllOfLinksInnerFromJSON(json: any): GetPage200ResponseAllOfLinksInner {
    return GetPage200ResponseAllOfLinksInnerFromJSONTyped(json, false);
}

export function GetPage200ResponseAllOfLinksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPage200ResponseAllOfLinksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GetPage200ResponseAllOfLinksInnerToJSON(value?: GetPage200ResponseAllOfLinksInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'text': value['text'],
        'url': value['url'],
    };
}

