/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetPage200ResponseAllOfPreregister } from './GetPage200ResponseAllOfPreregister';
import {
    GetPage200ResponseAllOfPreregisterFromJSON,
    GetPage200ResponseAllOfPreregisterFromJSONTyped,
    GetPage200ResponseAllOfPreregisterToJSON,
} from './GetPage200ResponseAllOfPreregister';
import type { WalletModel } from './WalletModel';
import {
    WalletModelFromJSON,
    WalletModelFromJSONTyped,
    WalletModelToJSON,
} from './WalletModel';
import type { AssetModel } from './AssetModel';
import {
    AssetModelFromJSON,
    AssetModelFromJSONTyped,
    AssetModelToJSON,
} from './AssetModel';
import type { GetPage200ResponseAllOfReferral } from './GetPage200ResponseAllOfReferral';
import {
    GetPage200ResponseAllOfReferralFromJSON,
    GetPage200ResponseAllOfReferralFromJSONTyped,
    GetPage200ResponseAllOfReferralToJSON,
} from './GetPage200ResponseAllOfReferral';
import type { GetPage200ResponseAllOfLeaderboard } from './GetPage200ResponseAllOfLeaderboard';
import {
    GetPage200ResponseAllOfLeaderboardFromJSON,
    GetPage200ResponseAllOfLeaderboardFromJSONTyped,
    GetPage200ResponseAllOfLeaderboardToJSON,
} from './GetPage200ResponseAllOfLeaderboard';
import type { GetPage200ResponseAllOfLinksInner } from './GetPage200ResponseAllOfLinksInner';
import {
    GetPage200ResponseAllOfLinksInnerFromJSON,
    GetPage200ResponseAllOfLinksInnerFromJSONTyped,
    GetPage200ResponseAllOfLinksInnerToJSON,
} from './GetPage200ResponseAllOfLinksInner';

/**
 * 
 * @export
 * @interface GetPage200Response
 */
export interface GetPage200Response {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    userId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    walletId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    iconImageAssetId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    backgroundImageAssetId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    logoImageAssetId?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof GetPage200Response
     */
    galleryMediaAssetIds?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    secretKey?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    testSecretKey?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    name?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    description?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    url?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    discordUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    twitterUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    steamUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    appleIosUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    appleMacUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    googlePlayUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    microsoftUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    privacyUrl?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    termsUrl?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof GetPage200Response
     */
    redirectUris?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    verificationStatus?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetPage200Response
     */
    createdAt?: string;
    /**
     * 
     * @type {AssetModel}
     * @memberof GetPage200Response
     */
    iconImageAsset?: AssetModel;
    /**
     * 
     * @type {AssetModel}
     * @memberof GetPage200Response
     */
    backgroundImageAsset?: AssetModel;
    /**
     * 
     * @type {AssetModel}
     * @memberof GetPage200Response
     */
    logoImageAsset?: AssetModel;
    /**
     * 
     * @type {Array<AssetModel>}
     * @memberof GetPage200Response
     */
    galleryMediaAssets?: Array<AssetModel>;
    /**
     * 
     * @type {GetPage200ResponseAllOfPreregister}
     * @memberof GetPage200Response
     */
    preregister?: GetPage200ResponseAllOfPreregister;
    /**
     * 
     * @type {GetPage200ResponseAllOfLeaderboard}
     * @memberof GetPage200Response
     */
    leaderboard?: GetPage200ResponseAllOfLeaderboard;
    /**
     * 
     * @type {GetPage200ResponseAllOfReferral}
     * @memberof GetPage200Response
     */
    referral?: GetPage200ResponseAllOfReferral;
    /**
     * 
     * @type {Array<GetPage200ResponseAllOfLinksInner>}
     * @memberof GetPage200Response
     */
    links?: Array<GetPage200ResponseAllOfLinksInner>;
    /**
     * 
     * @type {WalletModel}
     * @memberof GetPage200Response
     */
    wallet?: WalletModel;
    /**
     * 
     * @type {number}
     * @memberof GetPage200Response
     */
    totalUsers?: number;
}

/**
 * Check if a given object implements the GetPage200Response interface.
 */
export function instanceOfGetPage200Response(value: object): value is GetPage200Response {
    return true;
}

export function GetPage200ResponseFromJSON(json: any): GetPage200Response {
    return GetPage200ResponseFromJSONTyped(json, false);
}

export function GetPage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'walletId': json['walletId'] == null ? undefined : json['walletId'],
        'iconImageAssetId': json['iconImageAssetId'] == null ? undefined : json['iconImageAssetId'],
        'backgroundImageAssetId': json['backgroundImageAssetId'] == null ? undefined : json['backgroundImageAssetId'],
        'logoImageAssetId': json['logoImageAssetId'] == null ? undefined : json['logoImageAssetId'],
        'galleryMediaAssetIds': json['galleryMediaAssetIds'] == null ? undefined : json['galleryMediaAssetIds'],
        'secretKey': json['secretKey'] == null ? undefined : json['secretKey'],
        'testSecretKey': json['testSecretKey'] == null ? undefined : json['testSecretKey'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'discordUrl': json['discordUrl'] == null ? undefined : json['discordUrl'],
        'twitterUrl': json['twitterUrl'] == null ? undefined : json['twitterUrl'],
        'steamUrl': json['steamUrl'] == null ? undefined : json['steamUrl'],
        'appleIosUrl': json['appleIosUrl'] == null ? undefined : json['appleIosUrl'],
        'appleMacUrl': json['appleMacUrl'] == null ? undefined : json['appleMacUrl'],
        'googlePlayUrl': json['googlePlayUrl'] == null ? undefined : json['googlePlayUrl'],
        'microsoftUrl': json['microsoftUrl'] == null ? undefined : json['microsoftUrl'],
        'privacyUrl': json['privacyUrl'] == null ? undefined : json['privacyUrl'],
        'termsUrl': json['termsUrl'] == null ? undefined : json['termsUrl'],
        'redirectUris': json['redirectUris'] == null ? undefined : json['redirectUris'],
        'verificationStatus': json['verificationStatus'] == null ? undefined : json['verificationStatus'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'iconImageAsset': json['iconImageAsset'] == null ? undefined : AssetModelFromJSON(json['iconImageAsset']),
        'backgroundImageAsset': json['backgroundImageAsset'] == null ? undefined : AssetModelFromJSON(json['backgroundImageAsset']),
        'logoImageAsset': json['logoImageAsset'] == null ? undefined : AssetModelFromJSON(json['logoImageAsset']),
        'galleryMediaAssets': json['galleryMediaAssets'] == null ? undefined : ((json['galleryMediaAssets'] as Array<any>).map(AssetModelFromJSON)),
        'preregister': json['preregister'] == null ? undefined : GetPage200ResponseAllOfPreregisterFromJSON(json['preregister']),
        'leaderboard': json['leaderboard'] == null ? undefined : GetPage200ResponseAllOfLeaderboardFromJSON(json['leaderboard']),
        'referral': json['referral'] == null ? undefined : GetPage200ResponseAllOfReferralFromJSON(json['referral']),
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(GetPage200ResponseAllOfLinksInnerFromJSON)),
        'wallet': json['wallet'] == null ? undefined : WalletModelFromJSON(json['wallet']),
        'totalUsers': json['totalUsers'] == null ? undefined : json['totalUsers'],
    };
}

export function GetPage200ResponseToJSON(value?: GetPage200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'walletId': value['walletId'],
        'iconImageAssetId': value['iconImageAssetId'],
        'backgroundImageAssetId': value['backgroundImageAssetId'],
        'logoImageAssetId': value['logoImageAssetId'],
        'galleryMediaAssetIds': value['galleryMediaAssetIds'],
        'secretKey': value['secretKey'],
        'testSecretKey': value['testSecretKey'],
        'name': value['name'],
        'description': value['description'],
        'url': value['url'],
        'discordUrl': value['discordUrl'],
        'twitterUrl': value['twitterUrl'],
        'steamUrl': value['steamUrl'],
        'appleIosUrl': value['appleIosUrl'],
        'appleMacUrl': value['appleMacUrl'],
        'googlePlayUrl': value['googlePlayUrl'],
        'microsoftUrl': value['microsoftUrl'],
        'privacyUrl': value['privacyUrl'],
        'termsUrl': value['termsUrl'],
        'redirectUris': value['redirectUris'],
        'verificationStatus': value['verificationStatus'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
        'iconImageAsset': AssetModelToJSON(value['iconImageAsset']),
        'backgroundImageAsset': AssetModelToJSON(value['backgroundImageAsset']),
        'logoImageAsset': AssetModelToJSON(value['logoImageAsset']),
        'galleryMediaAssets': value['galleryMediaAssets'] == null ? undefined : ((value['galleryMediaAssets'] as Array<any>).map(AssetModelToJSON)),
        'preregister': GetPage200ResponseAllOfPreregisterToJSON(value['preregister']),
        'leaderboard': GetPage200ResponseAllOfLeaderboardToJSON(value['leaderboard']),
        'referral': GetPage200ResponseAllOfReferralToJSON(value['referral']),
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(GetPage200ResponseAllOfLinksInnerToJSON)),
        'wallet': WalletModelToJSON(value['wallet']),
        'totalUsers': value['totalUsers'],
    };
}

