/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWallet200Response
 */
export interface GetWallet200Response {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    type?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    address?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    authorityCiphertext?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof GetWallet200Response
     */
    authorityBackupCiphertexts?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    authorityProofSignature?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof GetWallet200Response
     */
    backupQuestions?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof GetWallet200Response
     */
    createdAt?: string;
    /**
     * The mainnet wallet implementation address to upgrade to if the wallet requires an upgrade, otherwise null if no upgrade required.
     * @type {string}
     * @memberof GetWallet200Response
     */
    mainnetRequiresUpgradeTo?: string;
    /**
     * The testnet wallet implementation address to upgrade to if the wallet requires an upgrade, otherwise null if no upgrade required.
     * @type {string}
     * @memberof GetWallet200Response
     */
    testnetRequiresUpgradeTo?: string;
    /**
     * The local wallet implementation address to upgrade to if the wallet requires an upgrade, otherwise null if no upgrade required.
     * @type {string}
     * @memberof GetWallet200Response
     */
    localRequiresUpgradeTo?: string;
}

/**
 * Check if a given object implements the GetWallet200Response interface.
 */
export function instanceOfGetWallet200Response(value: object): value is GetWallet200Response {
    return true;
}

export function GetWallet200ResponseFromJSON(json: any): GetWallet200Response {
    return GetWallet200ResponseFromJSONTyped(json, false);
}

export function GetWallet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWallet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'address': json['address'] == null ? undefined : json['address'],
        'authorityCiphertext': json['authorityCiphertext'] == null ? undefined : json['authorityCiphertext'],
        'authorityBackupCiphertexts': json['authorityBackupCiphertexts'] == null ? undefined : json['authorityBackupCiphertexts'],
        'authorityProofSignature': json['authorityProofSignature'] == null ? undefined : json['authorityProofSignature'],
        'backupQuestions': json['backupQuestions'] == null ? undefined : json['backupQuestions'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'mainnetRequiresUpgradeTo': json['mainnetRequiresUpgradeTo'] == null ? undefined : json['mainnetRequiresUpgradeTo'],
        'testnetRequiresUpgradeTo': json['testnetRequiresUpgradeTo'] == null ? undefined : json['testnetRequiresUpgradeTo'],
        'localRequiresUpgradeTo': json['localRequiresUpgradeTo'] == null ? undefined : json['localRequiresUpgradeTo'],
    };
}

export function GetWallet200ResponseToJSON(value?: GetWallet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'address': value['address'],
        'authorityCiphertext': value['authorityCiphertext'],
        'authorityBackupCiphertexts': value['authorityBackupCiphertexts'],
        'authorityProofSignature': value['authorityProofSignature'],
        'backupQuestions': value['backupQuestions'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
        'mainnetRequiresUpgradeTo': value['mainnetRequiresUpgradeTo'],
        'testnetRequiresUpgradeTo': value['testnetRequiresUpgradeTo'],
        'localRequiresUpgradeTo': value['localRequiresUpgradeTo'],
    };
}

