/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWhitelist200Response
 */
export interface GetWhitelist200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetWhitelist200Response
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetWhitelist200Response
     */
    userIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetWhitelist200Response
     */
    emails?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetWhitelist200Response
     */
    usernames?: Array<string>;
}

/**
 * Check if a given object implements the GetWhitelist200Response interface.
 */
export function instanceOfGetWhitelist200Response(value: object): value is GetWhitelist200Response {
    return true;
}

export function GetWhitelist200ResponseFromJSON(json: any): GetWhitelist200Response {
    return GetWhitelist200ResponseFromJSONTyped(json, false);
}

export function GetWhitelist200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWhitelist200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'userIds': json['userIds'] == null ? undefined : json['userIds'],
        'emails': json['emails'] == null ? undefined : json['emails'],
        'usernames': json['usernames'] == null ? undefined : json['usernames'],
    };
}

export function GetWhitelist200ResponseToJSON(value?: GetWhitelist200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': value['enabled'],
        'userIds': value['userIds'],
        'emails': value['emails'],
        'usernames': value['usernames'],
    };
}

