/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantSessionTokenRequest
 */
export interface GrantSessionTokenRequest {
    /**
     * An unused exchange code associated with the provided session id. Exchange codes can only be used once and then become invalid.
     * @type {string}
     * @memberof GrantSessionTokenRequest
     */
    exchangeCode: string;
}

/**
 * Check if a given object implements the GrantSessionTokenRequest interface.
 */
export function instanceOfGrantSessionTokenRequest(value: object): value is GrantSessionTokenRequest {
    if (!('exchangeCode' in value) || value['exchangeCode'] === undefined) return false;
    return true;
}

export function GrantSessionTokenRequestFromJSON(json: any): GrantSessionTokenRequest {
    return GrantSessionTokenRequestFromJSONTyped(json, false);
}

export function GrantSessionTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantSessionTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exchangeCode': json['exchangeCode'],
    };
}

export function GrantSessionTokenRequestToJSON(value?: GrantSessionTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exchangeCode': value['exchangeCode'],
    };
}

