/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NonceModel
 */
export interface NonceModel {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof NonceModel
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof NonceModel
     */
    walletId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof NonceModel
     */
    nonce?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof NonceModel
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the NonceModel interface.
 */
export function instanceOfNonceModel(value: object): value is NonceModel {
    return true;
}

export function NonceModelFromJSON(json: any): NonceModel {
    return NonceModelFromJSONTyped(json, false);
}

export function NonceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NonceModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'walletId': json['walletId'] == null ? undefined : json['walletId'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function NonceModelToJSON(value?: NonceModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'walletId': value['walletId'],
        'nonce': value['nonce'],
        'createdAt': value['createdAt'],
    };
}

