/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ReadContractArgsParameterInnerOneOfInner
 * 
 * @export
 */
export type ReadContractArgsParameterInnerOneOfInner = boolean | number | string;

export function ReadContractArgsParameterInnerOneOfInnerFromJSON(json: any): ReadContractArgsParameterInnerOneOfInner {
    return ReadContractArgsParameterInnerOneOfInnerFromJSONTyped(json, false);
}

export function ReadContractArgsParameterInnerOneOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadContractArgsParameterInnerOneOfInner {
    if (json == null) {
        return json;
    }
    if (instanceOfboolean(json)) {
        return booleanFromJSONTyped(json, true);
    }
    if (instanceOfnumber(json)) {
        return numberFromJSONTyped(json, true);
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ReadContractArgsParameterInnerOneOfInnerToJSON(value?: ReadContractArgsParameterInnerOneOfInner | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfboolean(value)) {
        return booleanToJSON(value as boolean);
    }
    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

