/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ReadContractArgsParameterInner
 * 
 * @export
 */
export type ReadContractArgsParameterInner = Array<ReadContractArgsParameterInnerOneOfInner> | boolean | number | string;

export function ReadContractArgsParameterInnerFromJSON(json: any): ReadContractArgsParameterInner {
    return ReadContractArgsParameterInnerFromJSONTyped(json, false);
}

export function ReadContractArgsParameterInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadContractArgsParameterInner {
    if (json == null) {
        return json;
    }
    if (instanceOfArray<ReadContractArgsParameterInnerOneOfInner>(json)) {
        return Array<ReadContractArgsParameterInnerOneOfInner>FromJSONTyped(json, true);
    }
    if (instanceOfboolean(json)) {
        return booleanFromJSONTyped(json, true);
    }
    if (instanceOfnumber(json)) {
        return numberFromJSONTyped(json, true);
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ReadContractArgsParameterInnerToJSON(value?: ReadContractArgsParameterInner | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfArray<ReadContractArgsParameterInnerOneOfInner>(value)) {
        return Array<ReadContractArgsParameterInnerOneOfInner>ToJSON(value as Array<ReadContractArgsParameterInnerOneOfInner>);
    }
    if (instanceOfboolean(value)) {
        return booleanToJSON(value as boolean);
    }
    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

