/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionModel
 */
export interface SessionModel {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    appId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    userId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    chain?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    accessToken?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    exchangeCode?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof SessionModel
     */
    scopes?: object;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof SessionModel
     */
    contractFunctionSelectors?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    nativeAllowance?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof SessionModel
     */
    erc20Allowances?: object;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof SessionModel
     */
    erc721Allowances?: object;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof SessionModel
     */
    erc1155Allowances?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    nonce?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof SessionModel
     */
    signatures?: object;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    deadline?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    expiresAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    endedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof SessionModel
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the SessionModel interface.
 */
export function instanceOfSessionModel(value: object): value is SessionModel {
    return true;
}

export function SessionModelFromJSON(json: any): SessionModel {
    return SessionModelFromJSONTyped(json, false);
}

export function SessionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'chain': json['chain'] == null ? undefined : json['chain'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'exchangeCode': json['exchangeCode'] == null ? undefined : json['exchangeCode'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'contractFunctionSelectors': json['contractFunctionSelectors'] == null ? undefined : json['contractFunctionSelectors'],
        'nativeAllowance': json['nativeAllowance'] == null ? undefined : json['nativeAllowance'],
        'erc20Allowances': json['erc20Allowances'] == null ? undefined : json['erc20Allowances'],
        'erc721Allowances': json['erc721Allowances'] == null ? undefined : json['erc721Allowances'],
        'erc1155Allowances': json['erc1155Allowances'] == null ? undefined : json['erc1155Allowances'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'signatures': json['signatures'] == null ? undefined : json['signatures'],
        'deadline': json['deadline'] == null ? undefined : json['deadline'],
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'endedAt': json['endedAt'] == null ? undefined : json['endedAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function SessionModelToJSON(value?: SessionModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'userId': value['userId'],
        'chain': value['chain'],
        'accessToken': value['accessToken'],
        'exchangeCode': value['exchangeCode'],
        'scopes': value['scopes'],
        'contractFunctionSelectors': value['contractFunctionSelectors'],
        'nativeAllowance': value['nativeAllowance'],
        'erc20Allowances': value['erc20Allowances'],
        'erc721Allowances': value['erc721Allowances'],
        'erc1155Allowances': value['erc1155Allowances'],
        'nonce': value['nonce'],
        'signatures': value['signatures'],
        'deadline': value['deadline'],
        'expiresAt': value['expiresAt'],
        'endedAt': value['endedAt'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
    };
}

