/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetAppState200Response
 */
export interface SetAppState200Response {
    /**
     * Public state data for the app or user.
     * @type {object}
     * @memberof SetAppState200Response
     */
    publicState: object;
    /**
     * Protected state data for the app or user.
     * @type {object}
     * @memberof SetAppState200Response
     */
    protectedState: object;
    /**
     * Private state data for the app or user.
     * @type {object}
     * @memberof SetAppState200Response
     */
    privateState?: object;
}

/**
 * Check if a given object implements the SetAppState200Response interface.
 */
export function instanceOfSetAppState200Response(value: object): value is SetAppState200Response {
    if (!('publicState' in value) || value['publicState'] === undefined) return false;
    if (!('protectedState' in value) || value['protectedState'] === undefined) return false;
    return true;
}

export function SetAppState200ResponseFromJSON(json: any): SetAppState200Response {
    return SetAppState200ResponseFromJSONTyped(json, false);
}

export function SetAppState200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetAppState200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'publicState': json['publicState'],
        'protectedState': json['protectedState'],
        'privateState': json['privateState'] == null ? undefined : json['privateState'],
    };
}

export function SetAppState200ResponseToJSON(value?: SetAppState200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'publicState': value['publicState'],
        'protectedState': value['protectedState'],
        'privateState': value['privateState'],
    };
}

