/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateModel
 */
export interface TemplateModel {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    userId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    name?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    description?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    solidity?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    target?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    bytecode?: string;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof TemplateModel
     */
    abi?: object;
    /**
     * This field has not had a description added.
     * @type {object}
     * @memberof TemplateModel
     */
    errors?: object;
    /**
     * This field has not had a description added.
     * @type {boolean}
     * @memberof TemplateModel
     */
    approved?: boolean;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof TemplateModel
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the TemplateModel interface.
 */
export function instanceOfTemplateModel(value: object): value is TemplateModel {
    return true;
}

export function TemplateModelFromJSON(json: any): TemplateModel {
    return TemplateModelFromJSONTyped(json, false);
}

export function TemplateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'solidity': json['solidity'] == null ? undefined : json['solidity'],
        'target': json['target'] == null ? undefined : json['target'],
        'bytecode': json['bytecode'] == null ? undefined : json['bytecode'],
        'abi': json['abi'] == null ? undefined : json['abi'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function TemplateModelToJSON(value?: TemplateModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'name': value['name'],
        'description': value['description'],
        'solidity': value['solidity'],
        'target': value['target'],
        'bytecode': value['bytecode'],
        'abi': value['abi'],
        'errors': value['errors'],
        'approved': value['approved'],
        'updatedAt': value['updatedAt'],
        'createdAt': value['createdAt'],
    };
}

