/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWhitelistRequest
 */
export interface UpdateWhitelistRequest {
    /**
     * Whether the whitelist is enabled.
     * @type {boolean}
     * @memberof UpdateWhitelistRequest
     */
    enabled?: boolean;
    /**
     * User Ids to add to the whitelist.
     * @type {Array<string>}
     * @memberof UpdateWhitelistRequest
     */
    userIds?: Array<string>;
    /**
     * Emails to add to the whitelist.
     * @type {Array<string>}
     * @memberof UpdateWhitelistRequest
     */
    emails?: Array<string>;
    /**
     * Usernames to add to the whitelist.
     * @type {Array<string>}
     * @memberof UpdateWhitelistRequest
     */
    usernames?: Array<string>;
}

/**
 * Check if a given object implements the UpdateWhitelistRequest interface.
 */
export function instanceOfUpdateWhitelistRequest(value: object): value is UpdateWhitelistRequest {
    return true;
}

export function UpdateWhitelistRequestFromJSON(json: any): UpdateWhitelistRequest {
    return UpdateWhitelistRequestFromJSONTyped(json, false);
}

export function UpdateWhitelistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWhitelistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'userIds': json['userIds'] == null ? undefined : json['userIds'],
        'emails': json['emails'] == null ? undefined : json['emails'],
        'usernames': json['usernames'] == null ? undefined : json['usernames'],
    };
}

export function UpdateWhitelistRequestToJSON(value?: UpdateWhitelistRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': value['enabled'],
        'userIds': value['userIds'],
        'emails': value['emails'],
        'usernames': value['usernames'],
    };
}

