/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateContractRequest
 */
export interface UpdateContractRequest {
    /**
     * JSON string of the contract's ABI.
     * @type {string}
     * @memberof UpdateContractRequest
     */
    abi?: string;
    /**
     * The contract's name. Named contracts are easier for users to identify during app or game authorization flows through HYPLAY.
     * @type {string}
     * @memberof UpdateContractRequest
     */
    name?: string;
    /**
     * A description of the contract and what it does.
     * @type {string}
     * @memberof UpdateContractRequest
     */
    description?: string;
    /**
     * A JSON string of arbitrary metadata for the contract. May be used by developers for a variety of reasons.
     * @type {string}
     * @memberof UpdateContractRequest
     */
    metadata?: string;
}

/**
 * Check if a given object implements the UpdateContractRequest interface.
 */
export function instanceOfUpdateContractRequest(value: object): value is UpdateContractRequest {
    return true;
}

export function UpdateContractRequestFromJSON(json: any): UpdateContractRequest {
    return UpdateContractRequestFromJSONTyped(json, false);
}

export function UpdateContractRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateContractRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'abi': json['abi'] == null ? undefined : json['abi'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateContractRequestToJSON(value?: UpdateContractRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'abi': value['abi'],
        'name': value['name'],
        'description': value['description'],
        'metadata': value['metadata'],
    };
}

