/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLeaderboardRequest
 */
export interface UpdateLeaderboardRequest {
    /**
     * The leaderboard name.
     * @type {string}
     * @memberof UpdateLeaderboardRequest
     */
    name?: string;
    /**
     * The leaderboard description.
     * @type {string}
     * @memberof UpdateLeaderboardRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateLeaderboardRequest interface.
 */
export function instanceOfUpdateLeaderboardRequest(value: object): value is UpdateLeaderboardRequest {
    return true;
}

export function UpdateLeaderboardRequestFromJSON(json: any): UpdateLeaderboardRequest {
    return UpdateLeaderboardRequestFromJSONTyped(json, false);
}

export function UpdateLeaderboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLeaderboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateLeaderboardRequestToJSON(value?: UpdateLeaderboardRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

