/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetPage200ResponseAllOfPreregister } from './GetPage200ResponseAllOfPreregister';
import {
    GetPage200ResponseAllOfPreregisterFromJSON,
    GetPage200ResponseAllOfPreregisterFromJSONTyped,
    GetPage200ResponseAllOfPreregisterToJSON,
} from './GetPage200ResponseAllOfPreregister';
import type { GetPage200ResponseAllOfReferral } from './GetPage200ResponseAllOfReferral';
import {
    GetPage200ResponseAllOfReferralFromJSON,
    GetPage200ResponseAllOfReferralFromJSONTyped,
    GetPage200ResponseAllOfReferralToJSON,
} from './GetPage200ResponseAllOfReferral';
import type { GetPage200ResponseAllOfLeaderboard } from './GetPage200ResponseAllOfLeaderboard';
import {
    GetPage200ResponseAllOfLeaderboardFromJSON,
    GetPage200ResponseAllOfLeaderboardFromJSONTyped,
    GetPage200ResponseAllOfLeaderboardToJSON,
} from './GetPage200ResponseAllOfLeaderboard';
import type { GetPage200ResponseAllOfLinksInner } from './GetPage200ResponseAllOfLinksInner';
import {
    GetPage200ResponseAllOfLinksInnerFromJSON,
    GetPage200ResponseAllOfLinksInnerFromJSONTyped,
    GetPage200ResponseAllOfLinksInnerToJSON,
} from './GetPage200ResponseAllOfLinksInner';

/**
 * 
 * @export
 * @interface UpdatePage200Response
 */
export interface UpdatePage200Response {
    /**
     * 
     * @type {GetPage200ResponseAllOfPreregister}
     * @memberof UpdatePage200Response
     */
    preregister?: GetPage200ResponseAllOfPreregister;
    /**
     * 
     * @type {GetPage200ResponseAllOfLeaderboard}
     * @memberof UpdatePage200Response
     */
    leaderboard?: GetPage200ResponseAllOfLeaderboard;
    /**
     * 
     * @type {GetPage200ResponseAllOfReferral}
     * @memberof UpdatePage200Response
     */
    referral?: GetPage200ResponseAllOfReferral;
    /**
     * 
     * @type {Array<GetPage200ResponseAllOfLinksInner>}
     * @memberof UpdatePage200Response
     */
    links?: Array<GetPage200ResponseAllOfLinksInner>;
}

/**
 * Check if a given object implements the UpdatePage200Response interface.
 */
export function instanceOfUpdatePage200Response(value: object): value is UpdatePage200Response {
    return true;
}

export function UpdatePage200ResponseFromJSON(json: any): UpdatePage200Response {
    return UpdatePage200ResponseFromJSONTyped(json, false);
}

export function UpdatePage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'preregister': json['preregister'] == null ? undefined : GetPage200ResponseAllOfPreregisterFromJSON(json['preregister']),
        'leaderboard': json['leaderboard'] == null ? undefined : GetPage200ResponseAllOfLeaderboardFromJSON(json['leaderboard']),
        'referral': json['referral'] == null ? undefined : GetPage200ResponseAllOfReferralFromJSON(json['referral']),
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(GetPage200ResponseAllOfLinksInnerFromJSON)),
    };
}

export function UpdatePage200ResponseToJSON(value?: UpdatePage200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'preregister': GetPage200ResponseAllOfPreregisterToJSON(value['preregister']),
        'leaderboard': GetPage200ResponseAllOfLeaderboardToJSON(value['leaderboard']),
        'referral': GetPage200ResponseAllOfReferralToJSON(value['referral']),
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(GetPage200ResponseAllOfLinksInnerToJSON)),
    };
}

