/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLeaderboard200Response
 */
export interface UpdateLeaderboard200Response {
    /**
     * The leaderboard ID.
     * @type {string}
     * @memberof UpdateLeaderboard200Response
     */
    id?: string;
    /**
     * The leaderboard name.
     * @type {string}
     * @memberof UpdateLeaderboard200Response
     */
    name?: string;
    /**
     * The leaderboard description.
     * @type {string}
     * @memberof UpdateLeaderboard200Response
     */
    description?: string;
    /**
     * The leaderboard scores, keyed by user ID.
     * @type {object}
     * @memberof UpdateLeaderboard200Response
     */
    scores?: object;
    /**
     * The leaderboard hash key, used to generate hashes
     * @type {string}
     * @memberof UpdateLeaderboard200Response
     */
    key?: string;
    /**
     * The timestamp of the leaderboard creation in seconds since the Unix epoch.
     * @type {number}
     * @memberof UpdateLeaderboard200Response
     */
    createdAt?: number;
}

/**
 * Check if a given object implements the UpdateLeaderboard200Response interface.
 */
export function instanceOfUpdateLeaderboard200Response(value: object): value is UpdateLeaderboard200Response {
    return true;
}

export function UpdateLeaderboard200ResponseFromJSON(json: any): UpdateLeaderboard200Response {
    return UpdateLeaderboard200ResponseFromJSONTyped(json, false);
}

export function UpdateLeaderboard200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLeaderboard200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'scores': json['scores'] == null ? undefined : json['scores'],
        'key': json['key'] == null ? undefined : json['key'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function UpdateLeaderboard200ResponseToJSON(value?: UpdateLeaderboard200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'scores': value['scores'],
        'key': value['key'],
        'createdAt': value['createdAt'],
    };
}

