/* tslint:disable */
/* eslint-disable */
/**
 * HYPLAY API
 * HYPLAY API Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: braydon@hytopia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAppTeammateRequest
 */
export interface UpdateAppTeammateRequest {
    /**
     * The role of the teammate.
     * @type {string}
     * @memberof UpdateAppTeammateRequest
     */
    role: UpdateAppTeammateRequestRoleEnum;
}


/**
 * @export
 */
export const UpdateAppTeammateRequestRoleEnum = {
    Owner: 'OWNER',
    Developer: 'DEVELOPER',
    Editor: 'EDITOR',
    Analyst: 'ANALYST'
} as const;
export type UpdateAppTeammateRequestRoleEnum = typeof UpdateAppTeammateRequestRoleEnum[keyof typeof UpdateAppTeammateRequestRoleEnum];


/**
 * Check if a given object implements the UpdateAppTeammateRequest interface.
 */
export function instanceOfUpdateAppTeammateRequest(value: object): value is UpdateAppTeammateRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UpdateAppTeammateRequestFromJSON(json: any): UpdateAppTeammateRequest {
    return UpdateAppTeammateRequestFromJSONTyped(json, false);
}

export function UpdateAppTeammateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAppTeammateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function UpdateAppTeammateRequestToJSON(value?: UpdateAppTeammateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': value['role'],
    };
}

